#### 🧪 Real Interview Level Questions
1. Find second largest element using NumPy  
2. Remove duplicates from array  
3. Reverse array without loop  
4. Find indices where value > 5  
5. Replace all negative values with 0  
6. Count number of even numbers  
7. Merge two arrays  
8. Find common elements between two arrays  
9. Sort array row-wise  
10. Create checkerboard pattern matrix  

In [ ]:
import numpy as np


In [55]:
# second largest
arr = np.array([-1,-2,-4,-3,1,2,3,3,4,5,7,8,9])
large = np.max(arr)
sum = np.sum(arr[arr>=3])
print(sum)

print(large)
print(arr)



# reverse array without loops
rev = arr[::-1]
print(rev)
# other with method
reverse = np.flip(arr)
print(reverse)

# remove duplicates
unique = np.unique(arr)
print(unique)


# find indices where value >5
indices = np.where(arr[arr>5])[0]   # single [0] for 1 array and [0][0] for 2d array

print(indices)

# replace -ve with 0s
arr[arr<0] = 0
# other way
replace = np.where(arr<0,0,arr)
print(arr)
print(replace)


sizes = np.size(arr2)
print(sizes)

print(arr)

39
9
[-1 -2 -4 -3  1  2  3  3  4  5  7  8  9]
[ 9  8  7  5  4  3  3  2  1 -3 -4 -2 -1]
[ 9  8  7  5  4  3  3  2  1 -3 -4 -2 -1]
[-4 -3 -2 -1  1  2  3  4  5  7  8  9]
[0 1 2]
[0 0 0 0 1 2 3 3 4 5 7 8 9]
[0 0 0 0 1 2 3 3 4 5 7 8 9]
7
[0 0 0 0 1 2 3 3 4 5 7 8 9]
