In [34]:
import numpy as np
import time
import sys #this package i use for the memore occupy

In [24]:
arr  = np.array([1,2,3,4,2,73,"dgc","ahjcja","cjbds"])
print(arr)

['1' '2' '3' '4' '2' '73' 'dgc' 'ahjcja' 'cjbds']


1. numpy arrays are faster than the python lists /n 
to check that we compate thetime of execution by using time package

In [42]:
target = 10_00_000 #if the terget value is like 1billion then the kernel crash 
pyt_list = list(range(target)) #python list
print(type(pyt_list)) 
start = time.time() #give the time
sq_root_list = [x**2 for x in pyt_list]
end = time.time()
print(f"time required {end - start}sec")


arr = np.array(range (target))
start = time.time()
#vectorization
sq_root_nparray = arr**2
end = time.time()
print(f"numpy arrays time {end-start}sec")


<class 'list'>
time required 1.7022945880889893sec
numpy arrays time 0.020330429077148438sec


2 . numpy stored data in continous memory blocks

while lists are in non-contigeous



In [53]:
# memory occupy comparision
import numpy as np 

mem_pythlist = sys.getsizeof(pyt_list)+sum(sys.getsizeof(i) for i in pyt_list) # for each list items the memory size 
# mem_arr = sys.getsizeof(arr)*len(arr) # for each array items the memory size 
mem_arr2 = arr.nbytes  # nbytes return the size of memory occupy by the every elements in an array
# internally the ( .size * .itemsize)
print(mem_pythlist)
print(mem_arr2)

mem_arr3 = np.array([12,13,1,234],dtype="U21")
print(mem_arr3.dtype)

36000056
8000000
<U21


In [ ]:
arr =np.array([[1,2,3,4],[3,2,4,5]])
print(arr.itemsize)   #it return the size of 1 interms of byte which is equals o 8 byte
print(arr)

8
[[1 2 3 4]
 [3 2 4 5]]


In [ ]:
arr2D = np.zeros((2,3)) 
arr2D = np.ones((2,3)) 
arr2D = np.full((2,3),29) 
arr2D = np.eye((4))  #identity matrix
arr2D = np.linspace(1,100,4)  #identity matrix
arr2D = np.arange(1,100,2) #print odd matrix
arr2D = np.linspace(1,100,4)  #identity matrix

print(arr2D,arr2D.shape)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
