In [2]:
import numpy as np
import time
import sys #this package i use for the memore occupy

In [2]:
arr  = np.array([1,2,3,4,2,73,"dgc","ahjcja","cjbds"])
print(arr)

['1' '2' '3' '4' '2' '73' 'dgc' 'ahjcja' 'cjbds']


1. numpy arrays are faster than the python lists /n 
to check that we compate thetime of execution by using time package

In [3]:
target = 10_00_000 #if the terget value is like 1billion then the kernel crash 
pyt_list = list(range(target)) #python list
print(type(pyt_list)) 
start = time.time() #give the time
sq_root_list = [x**2 for x in pyt_list]
end = time.time()
print(f"time required {end - start}sec")


arr = np.array(range (target))
start = time.time()
#vectorization
sq_root_nparray = arr**2
end = time.time()
print(f"numpy arrays time {end-start}sec")


<class 'list'>
time required 0.2631545066833496sec
numpy arrays time 0.007227420806884766sec


2 . numpy stored data in continous memory blocks

while lists are in non-contigeous



In [4]:
# memory occupy comparision
import numpy as np 

mem_pythlist = sys.getsizeof(pyt_list)+sum(sys.getsizeof(i) for i in pyt_list) # for each list items the memory size 
# mem_arr = sys.getsizeof(arr)*len(arr) # for each array items the memory size 
mem_arr2 = arr.nbytes  # nbytes return the size of memory occupy by the every elements in an array
# internally the ( .size * .itemsize)
print(mem_pythlist)
print(mem_arr2)

mem_arr3 = np.array([12,13,1,234],dtype="U21")
print(mem_arr3.dtype)

36000056
8000000
<U21


In [5]:
arr =np.array([[1,2,3,4],[3,2,4,5]])
print(arr.itemsize)   #it return the size of 1 interms of byte which is equals o 8 byte
print(arr)

8
[[1 2 3 4]
 [3 2 4 5]]


In [6]:
arr2D = np.zeros((2,3)) 
arr2D = np.ones((2,3)) 
arr2D = np.full((2,3),29) 
arr2D = np.eye((4))  #identity matrix
arr2D = np.linspace(1,100,4)  #identity matrix
arr2D = np.arange(1,100,2) #print odd matrix
arr2D = np.linspace(1,100,4)  
print(arr2D,arr2D.shape)


[  1.  34.  67. 100.] (4,)


In [4]:
import numpy as np
arr = np.array([[1,2,1,3,1,3,4],[1,2,1,3,4,2,6]])
print(np.ndim(arr))

2


In [15]:
lst = [2,3,3,2,2]
arr=np.array(lst)
arr2 = np.asarray(arr)
arr[0] = 100
print(arr)
print(arr2)
print(lst)

[100   3   3   2   2]
[100   3   3   2   2]
[2, 3, 3, 2, 2]


In [23]:
arr = np.array([2+3j])
arr2 = np.array([4+3j])
print(arr+arr2)


arr3 = np.array([1,2,3,4,2.3,{1,2,4},-1,5,6,7],dtype = "str")
arr4 = arr3.astype(object)
print(arr4,arr4.dtype)
print(arr3,arr3.dtype)


[6.+6.j]
['1' '2' '3' '4' '2.3' '{1, 2, 4}' '-1' '5' '6' '7'] object
['1' '2' '3' '4' '2.3' '{1, 2, 4}' '-1' '5' '6' '7'] <U9


In [28]:
# Normalization
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)
print(mean)
print(std)

normalization = (arr-mean)/std
print(normalization)

idx_diff = arr-normalization
print(idx_diff)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[2.34164079 2.4472136 ]
 [2.5527864  2.65835921]]


In [ ]:
# argmin(), argmax(), pow() , round(), floor(), ceil(), trunc(), unique(), sort(), abs(), exp(), 

arr = np.array([1,2,3,4,4,5,6])

arr2 = np.array([1.23,1.65,1.89])
argmin  = np.argmin(arr) # minimum element index found
argmax  = np.argmax(arr) # maximum element index found

power = np.pow(arr,2)
round = np.round(arr2) # roundfigure the float value with the nearest integer
floor = np.floor(arr2) # define the lower value in the decimal
ceil = np.ceil(arr2) # define the upper value

trunc = np.trunc(arr2) # removes the digits after the decemal number

print(argmin)
print(argmax)

print(power)
print(round)
print(floor)
print(ceil)

print(trunc)
print(arr2)



0
6
[ 1  4  9 16 16 25 36]
[1. 2. 2.]
[1. 1. 1.]
[2. 2. 2.]
[1. 1. 1.]
[1.23 1.65 1.89]
