🧠 NumPy Mastery Question Set  
🟢 1. Basics + Array Creation  

Create a NumPy array from a Python list [1,2,3,4,5]  
Create:  
all zeros array (3x3)  
all ones array (2x4)  
identity matrix (4x4)  
Create an array with values from 10 to 50 with step 5   
Create a random array of size (3,3)  
What is the difference between np.array() and np.asarray()?

In [4]:
import numpy as np
import random
import time

In [3]:
li = [1,22,1,1,3,7,5]
arr = np.array(li)
print(arr)

[ 1 22  1  1  3  7  5]


In [6]:
# all zeros array
arr_zero = np.zeros((3,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# all ones array (2x4)
arr_ones = np.ones((2,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# identity matrix (4x4)
arr_identity = np.eye((4))
print(arr_identity,arr_identity.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Create an array with values from 10 to 50 with step 5
arr_step = np.arange(10,50,5) #range items ithin the values 
print(arr_step,arr.shape)

[10 15 20 25 30 35 40 45] (7,)


In [ ]:
# Create a random array of size (3,3)
rand = random.randint(1,100)  #random number generator
random_num_arr = np.full((3,3),rand)
print(random_num_arr)


[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [ ]:
# What is the difference between np.array() and np.asarray()?
# as arrays behabe like = like arr2 = arr any changes in array 2 shoul hamper the arrar1 
# asarray dont made instaed copy instaed of that it pointing to the same array
# but incase of array it creates a copy so that the changes in array2 doesnot make changes in arrsy 1 

lst = [2,3,3,2,2]
arr=np.array(lst)
arr2 = np.asarray(arr)
# arr2 =arr
arr[0] = 100
print(arr)
print(arr2)
print(lst)

🟢 2. Python List vs NumPy Array  
 
Why NumPy is faster than Python list? (practical explanation)  
Multiply all elements by 2:  
using list  
using numpy  
What happens when you do:   
arr = np.array([1,2,3])  
arr + 5  
Memory difference concept (theory + small demo)

In [46]:
# the biultin methods in which are called vectorization fats up the operation instead of taking loops
# numpy is implemented in c which is near to system npt purely create in python
# they are having the homogeneous and contiguous memory location so that that store in the sytem cachewhich is faster memory
num =100_000
li = list(range(num))
arr = np.array(li)
start = time.time()
Squre = [i*2 for i in li]
end = time.time()
print(end - start)

start = time.time()
squre = np.multiply(arr,2)
end = time.time()

print(end - start)
# print(arr)

0.009600639343261719
0.019484519958496094


In [ ]:
arr = np.array([[1,2,3],[1,3,2]])
arr2 = np.array([[2,3,2],[4,2,5],[6,3,8]])
arr3 = arr+arr2  #this is called broadcasting python autometovcally convert the scaler 5 into the array form only of the dimentions are (n x m and n x m) or (n x m  and 1 x m or n x 1 )

print(arr3)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
# Python list stores references (pointers), while NumPy array stores raw data in contiguous memory, making it more memory efficient.


[1, 2, 3, 4]
[2, 777, 4]
[   2 2626    6    4]
[  11    2 2626    6    4    3]


🟡 3. Array Properties

Given:  
arr = np.array([[1,2,3],[4,5,6]])  
Find:  
shape  
ndim  
size  
dtype  
Convert dtype from int → float  
Flatten the array  

In [73]:
arr = np.array([[1,2,3],[4,5,6]])  
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)
print(arr.size)
new_array = arr.astype(float)
print(new_array.dtype)


int64
(2, 3)
8
6
float64


In [85]:
# flatten the array
arr2D = np.array([[1,2,3],[4,5,6]])  
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,8,7]]])  
arr2Di  = arr2D.flatten()
arr3Di  = arr3D.flatten()
print(f"3d array is \n {arr3D}")
print(f"3d flatten array is \n{arr3Di}")
print(f"2d array is \n {arr2D}")
print(f"2d flatten array is \n{arr2Di}")

3d array is 
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 8 7]]]
3d flatten array is 
[1 2 3 4 5 6 7 8 9 0 8 7]
2d array is 
 [[1 2 3]
 [4 5 6]]
2d flatten array is 
[1 2 3 4 5 6]


🟡 4. Indexing & Slicing  

Get element 5 from:  
[[1,2,3],  
 [4,5,6]]   

Extract:  

first row  
last column  

Slice:  
[2,3,4] from [1,2,3,4,5]  

Modify slice and check original array → why it changes?  

In [ ]:
arr2D = np.array([[1,2,3],[4,5,6]])  
elem = arr2D[1][1] # row and column using 
print(elem)

5


In [92]:
first_row = arr2D[:1 ,:]
print(first_row)

last_column =arr2D[:,2:]
print(last_column)

[[1 2 3]]
[[3]
 [6]]


In [93]:
arr2D = np.array([1,2,3,4,5])
slice_elem = arr2D[1:4]
print(slice_elem) 

[2 3 4]


In [97]:
#lists creates reference while array creates view
# a → [1, 2, 3, 4,]
#         ↑  ↑  ↑
#       cop cop cop  

li = [1,2,3,4]
copy  = li[1:4]
copy[1] = 777
print(li)  #no changes because they are references 
print(copy)


arr = np.array([11,2,3,6,4,3])
arr2 = arr[1:5]
arr2[1]  =2626   # chamges due to view
# arr2 = arr[2:3]
print(arr2)
print(arr)


# copy in safe way in array
arr3  = np.array([1,2,3,4,5])
arr_copy = arr3[1:4].copy()
print(arr3)
print(arr_copy)

[1, 2, 3, 4]
[2, 777, 4]
[   2 2626    6    4]
[  11    2 2626    6    4    3]
[1 2 3 4 5]
[2 3 4]


🟡 5. Copy vs View (IMPORTANT 🔥)  

Create array and assign:  

b = a

Modify b, what happens to a?  

Use .copy() and check difference  
Use .view() and test behavior  
Explain:  
👉 Why slicing returns view not copy?  

In [ ]:
# view() creates a new array object that shares the same underlying data buffer, so changes reflect in both arrays
# in case of copy object the different ojects are pointng to different memory
arr = np.array([1,2,3,4,5,6])
arr2 =arr.view()
x = arr2[:3]
x[0] =999
print(arr2)
print(arr)
print(x)

arr = np.array([11,2,3,6,4,3])
arr2 = arr[1:5]
arr2[1]  =2626   # chamges due to view
# arr2 = arr[2:3]
print(arr2)
print(arr)


[999   2   3   4   5   6]
[999   2   3   4   5   6]
[999   2   3]


🟠 6. Reshaping & Dimensions  
Convert:  
(1D → 2D)  
(2D → 1D)  

Reshape:  

arr = np.arange(12)  

into:  

(3,4)  
(2,6)  
What happens if reshape size doesn’t match? 
Use -1 in reshape (auto dimension)  

In [ ]:
arr = np.array([11,2,3,6,4,3])
shaped = arr.reshape(2,3)
print(shaped,shaped.shape)   #1d to 2d

reshaped = shaped.reshape(6)  #2d to 1d
print(reshaped,reshaped.shape)




[[11  2  3]
 [ 6  4  3]] (2, 3)
[11  2  3  6  4  3] (6,)


In [ ]:
arr = np.arange(12)
shape_3_4= arr.reshape(3,4)
shape_3_4= arr.reshape(3,-1)
# -1 for auto dimentions

shape_2_6 = arr.reshape(2,6)
shape_2_6 = arr.reshape(2,-1)

print(shape_3_4)
print(shape_2_6)

ValueError: cannot reshape array of size 12 into shape (3,1)

In [ ]:
# if the reshape doesnt match then value error is cannot reshape array of size x into shape (x,y) or else

🟠 7. Multi-dimensional & 3D Arrays  
Create a 3D array manually   
Access:  
first matrix  
specific element  
What is axis?  
Difference between axis=0, axis=1, axis=2  

In [137]:
arr3D = np.array([[[6,7],[8,9]],[[2,3],[4,5]]])
print("full array \n",arr3D)
print("first matrix \n",arr3D[0])

#specific element
spec = arr3D[0,1:,1:]
print(spec)

full array 
 [[[6 7]
  [8 9]]

 [[2 3]
  [4 5]]]
first matrix 
 [[6 7]
 [8 9]]
[[9]]


In [ ]:
# axis are defines the directions of the array such as axis =0 is 1d arrat   axis=1 is 2d array axis = 3 is 3d array
# thats the varience of axis

arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,0],[11,12]]])
print(arr)
axis_2 = np.sum((arr),axis =2) #column top tobottom collapse
axis_1 = np.sum((arr),axis =1) #row  left to right collapse
axis_0 = np.sum((arr),axis =0) #layer  arrays are collapse in both directions
print(axis_0)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]]
[[ 8 10]
 [12  4]
 [16 18]]


## 🔵 8. Vectorization & Broadcasting (VERY IMPORTANT 🚀)  
Add two arrays without loop  
Multiply array by scalar  

Broadcasting case:

A = [[1,2,3],  
  [4,5,6]]  
B = [1,2,3]  

→ result?  

Why broadcasting is powerful?  
When broadcasting fails?  

In [155]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
# arr3 = np.add(arr,arr2)
arr3=arr2+arr
print(arr3)

[ 2  4  6  8 10]


In [ ]:
A = [[1,2,3],  
  [4,5,6]]  

a = np.array(A)
B = [1,2,3]  

b = np.array(B)

result = a+B
print(result) 


[[2 4 6]
 [5 7 9]]


In [ ]:
#broadcasting is powerful because instead of definig full array the scalar expands it self acording to the other array size
# the broadcasting fails where the dimenstions are not same and not in 1 x m array
 

🔵 8. Vectorization & Broadcasting (VERY IMPORTANT 🚀)  
Add two arrays without loop  
Multiply array by scalar  

Broadcasting case:  

A = [[1,2,3],  
     [4,5,6]]  
B = [1,2,3]   

→ result?  

Why broadcasting is powerful?  
When broadcasting fails?  

In [ ]:
A = [[1,2,3],  
  [4,5,6]]  
x= np.array(A)
y = x*3
print(y)



[[ 3  6  9]
 [12 15 18]]


In [ ]:
# Broadcasting allows NumPy to perform operations on arrays of different shapes without copying data, but it fails when dimensions are incompatible.
# fast performance
# efficient memory usage
# less code
# different dimention

### 🔵 9. Vector Normalization

Normalize:  

[3,4]  
Formula:  
👉 x / ||x||  
Normalize each row of a matrix  
Why normalization is important in ML?

In [ ]:
arr = np.array([3,4])
# for normalize formula
# (array - mean)/std_dev

mean = np.mean(arr)
std_dev = np.std(arr)
normalization  = (arr-mean)/std_dev
print(normalization)
print(mean)
print(std_dev)



[-1.  1.]
3.5
0.5


###  🔵 10. Mean & Standard Deviation
Calculate mean of array  
Calculate:  
row-wise mean  
column-wise mean  
Standard deviation:  
overall  
axis-based  
Difference between variance & std deviation

In [14]:
arr = np.array([[1,2,3],[4,5,6]])

mean_col = np.mean(arr,axis = 1)
mean_row = np.mean(arr,axis = 0)
print(arr)
print(mean_row)
print(mean_col)


[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]
[2. 5.]


In [20]:
std_ax0 = np.std(arr,axis=0)
std_ax1 = np.std(arr,axis=1)
var = np.var(arr)
print(vas)
print(std_ax0)
print(std_ax1)

2.9166666666666665
[1.5 1.5 1.5]
[0.81649658 0.81649658]


🔵 11. Aggregate Functions

Given array:

arr = np.array([[1,2,3],[4,5,6]])
Find:
sum
min
max
Axis-based:
sum of rows
sum of columns
Find index of max value
Difference:
np.sum() vs Python sum()

In [28]:
arr = np.array([[2,4,3],[1,5,6]])
print(np.sum(arr,axis = 1)) # column wise
print(np.sum(arr,axis = 0)) # row wise
print(np.sum(arr)) # overall

min = np.min(arr)
max = np.max(arr)

print(min)
print(max)

max_index = np.where(arr == min)[0][0]  # using conditions

argmin = np.argmin(arr)
argmax = np.argmax(arr)

print(max_index)
print(arr,max_index)
print(argmin)
print(argmax)




[ 9 12]
[3 9 9]
21
1
6
1
[[2 4 3]
 [1 5 6]] 1
3
5


🔴 12. Advanced Math Functions
Apply:
sin
cos
log
Square each element
Find square root of array
Clip values between range (e.g., 2–5)

In [ ]:
print(np.sin(arr))
print(np.cos(arr))
print(np.square(arr))
print(np.log10(arr))
print(np.sqrt(arr))


arr = np.array([1,2,3.3,2.3,1.6,6,7,88,9,4])
clip = np.clip(arr,2,6)   # clip the value in range 2 to 6 
# value<2 becomes 2 then value>6 becomes 6

print(clip)

[ 0.84147098  0.90929743 -0.15774569  0.74570521  0.9995736  -0.2794155
  0.6569866   0.0353983   0.41211849 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.98747977 -0.66627602 -0.02919952  0.96017029
  0.75390225  0.99937328 -0.91113026 -0.65364362]
[1.000e+00 4.000e+00 1.089e+01 5.290e+00 2.560e+00 3.600e+01 4.900e+01
 7.744e+03 8.100e+01 1.600e+01]
[0.         0.30103    0.51851394 0.36172784 0.20411998 0.77815125
 0.84509804 1.94448267 0.95424251 0.60205999]
[1.         1.41421356 1.81659021 1.51657509 1.26491106 2.44948974
 2.64575131 9.38083152 3.         2.        ]
[2.  2.  3.3 2.3 2.  6.  6.  6.  6.  4. ]
